#!/bin/bash
# program for calculate statistic

#echo "Hello World"
#myname="Aldiansyah Suryoutomo"
#echo $myname

success=0
fail=1

if [[ ! -z $2 && ! -r $2 ]];
then
	echo "$0: cannot read $2" 1>&2
	exit $fail
fi

#give some error comment if user doesn't write the command correctly
error () {
	echo "$0 {-rows|-cols} [file]"
}


if [[ $# > 2 ]];
then
	error
	exit $fail
fi

#argument to calculate rows number, begin with -r
if [[ $1 == -r* ]];
then
	echo -e "Average\tMedian"
	while read myfile
	do
		#initialization variable before calculate average
		sum=0
		count=0
		ave=0
		
		sort_myfile=$(echo "$myfile" | expand | tr ' ' '\n' | sed '/^$/d' | sort -n | tr '\n' ' ')
		array=($sort_myfile)
		len=${#array[@]}
		mid=$(expr $len / 2)
		median=${array[mid]}
		#forloop is used to count average of each rows
		for i in $myfile
		do
			count=`expr $count + 1`	
			sum=`expr $sum + $i`
			ave=$((($sum + ($count / 2)) / $count))
		done
		echo -e "$ave\t$median"
		#echo -e "$mid\n"
	done < "${2:-/dev/stdin}"


elif [[ $1 == -c* ]];
then
	#read line
	#echo "under construction"
	tempfile=""
	while read line
	do
		tempfile+=$line
		tempfile+=$'\n'
	done < "${2:-dev/stdin}"

	first_arr=($(printf "%s\n" "$tempfile" | head -1))
	
	len_arr=${#first_arr[@]}

	aver=()
	med=()
	#success=0
	#fail=1

	if [[ $len_arr == 0 ]];
	then
		echo Averages:
		echo -e "\n"
		echo Medians:
		echo -e "\n"
		exit $success
	fi
		#echo "$line_len"

	for i in $(seq 1 $len_arr)
	do
			numb=$(printf "%s\n" "$tempfile" | cut -f $i | sort -n | tr '\n' ' ')
			new_arr=($numb)
			ctr=$(expr ${#new_arr[@]} / 2)
			mean=${new_arr[$ctr]}
			means+=($mean)
			sum=$(echo $numb | sed 's/ / + /g')
			round_function=$(expr \( ${#new_arr[@]} \) / 2 )
			ave=$(expr \( $sum + $round_function \) / ${#new_arr[@]})
			average+=($ave)
			
	done
	#done < "${2:-/dev/stdin}"
	
	#echo -e "X:\n$tempfile"
	#echo "mean: $mean"
	#echo "total column: $len_arr "
	#echo "mid: $ctr"
	#echo "sum: $sum"
	echo Averages:
	echo -e "${average[@]}"
	echo Median:
	echo -e "${means[@]}"
	#file=$1
	#echo
	
	#numrows=1
	#while read -r -a array
	#do
	#	((numrows++))
	#	for i in "${array[@]}"
	#	do
	#		column[i]+="$array[i]"$'\n'
	#	done
	#done < $file

	#midrow=$((1+numrows/2))
	#echo "$midrow"

	#result=''
	#for i in "${!column[@]}"
	#do
	#	median=$(sort -n <<<"${column[i]}" | head -n "$midrow" | tail -n 1)
	#	result+="$median "
	#done <$1

	#echo "Average: "
	#echo "still under construction"
	#echo "Median: $result"
else
	error
	exit $fail
fi

#read File

#while read num
#do
#	sum=0
#	count=0
#	ave=0
#	for i in $num
#	do
#		sum=$(($sum + $i))
#		#count=$((count + 1))
#		#ave=$((($sum + ($count / 2)) / $count))
#	done
#	echo "$sum"
#	echo "$num Sum: $sum  average: $ave"
#done < $File
