#!/bin/bash
sum=0
count=0
ave=0
TMP1=./tempfile
echo -e "8\n7\n6" > $TMP1

while read num
do
	echo "in Loop"
	echo "num= $num"
	sum=$((sum+num))
	count=$((count+1))
	ave=$((sum/count))
	echo "sum= $sum"
	echo "ave= $ave"
	echo -e "end of loop\n"
done < $TMP1
